language: node_js
sudo: false
node_js:
    - '8.16.0'
jobs:
    include:
        - stage: unit-tests
          script: npm test

notifications:
    webhooks:
        urls:
            - http://3.16.184.186:3000/notifications
